# version: '3.8'
services:

  phoenixbits:
    container_name: phoenixbits
    #image: pastagringo/lnbits-phoenixbits
    build:
      context: .
    volumes:
      - ./phoenixbits/lnbits/data:/app/data
    environment:
      - LNBITS_SITE_TITLE=${LNBITS_SITE_TITLE}
      - LNBITS_SITE_TAGLINE=${LNBITS_SITE_TAGLINE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phoenixbits.rule=Host(`${PHOENIXBITS_DOMAIN}`)"
      - "traefik.http.services.phoenixbits.loadbalancer.server.port=5000"
      - "traefik.http.routers.phoenixbits.service=phoenixbits"
      - "traefik.http.routers.phoenixbits.entrypoints=websecure"
      - "traefik.http.routers.phoenixbits.tls.certresolver=selfhostedservices"
#      - "traefik.http.routers.phoenixbits.middlewares=accesscontrol@docker"

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.selfhostedservices.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.selfhostedservices.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.selfhostedservices.acme.storage=/letsencrypt/acme.json"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=INFO"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
